# **⭐ Classification Model to Identify Multiple Disease**

In [4]:
# import library
import pandas as pd
import numpy as py
import matplotlib.pyplot as plt
import seaborn as sns
import missingno as msno

In [5]:
# import data
disease = pd.read_csv('https://github.com/YBI-Foundation/Dataset/raw/main/MultipleDiseasePrediction.csv')

In [6]:
# view data
disease.head()

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  shivering  \
0        1          1                     1                    0          0   
1        0          1                     1                    0          0   
2        1          0                     1                    0          0   
3        1          1                     0                    0          0   
4        1          1                     1                    0          0   

   chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  ...  \
0       0           0             0        0                 0  ...   
1       0           0             0        0                 0  ...   
2       0           0             0        0                 0  ...   
3       0           0             0        0                 0  ...   
4       0           0             0        0                 0  ...   

   blackheads  scurring  skin_peeling  silver_like_dusting  \
0           0         0             0                    0   
1           0         0             0                    0   
2           0         0             0                    0   
3           0         0             0                    0   
4           0         0             0                    0   

   small_dents_in_nails  inflammatory_nails  blister  red_sore_around_nose  \
0                     0                   0        0                     0   
1                     0                   0        0                     0   
2                     0                   0        0                     0   
3                     0                   0        0                     0   
4                     0                   0        0                     0   

   yellow_crust_ooze         prognosis  
0                  0  Fungal infection  
1                  0  Fungal infection  
2                  0  Fungal infection  
3                  0  Fungal infection  
4                  0  Fungal infection  

[5 rows x 133 columns]

In [7]:
# info of data
disease.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4920 entries, 0 to 4919
Columns: 133 entries, itching to prognosis
dtypes: int64(132), object(1)
memory usage: 5.0+ MB


In [8]:
# summary statistics
disease.describe()

itching    skin_rash  nodal_skin_eruptions  continuous_sneezing  \
count  4920.000000  4920.000000           4920.000000          4920.000000   
mean      0.137805     0.159756              0.021951             0.045122   
std       0.344730     0.366417              0.146539             0.207593   
min       0.000000     0.000000              0.000000             0.000000   
25%       0.000000     0.000000              0.000000             0.000000   
50%       0.000000     0.000000              0.000000             0.000000   
75%       0.000000     0.000000              0.000000             0.000000   
max       1.000000     1.000000              1.000000             1.000000   

         shivering       chills   joint_pain  stomach_pain      acidity  \
count  4920.000000  4920.000000  4920.000000   4920.000000  4920.000000   
mean      0.021951     0.162195     0.139024      0.045122     0.045122   
std       0.146539     0.368667     0.346007      0.207593     0.207593   
min       0.000000     0.000000     0.000000      0.000000     0.000000   
25%       0.000000     0.000000     0.000000      0.000000     0.000000   
50%       0.000000     0.000000     0.000000      0.000000     0.000000   
75%       0.000000     0.000000     0.000000      0.000000     0.000000   
max       1.000000     1.000000     1.000000      1.000000     1.000000   

       ulcers_on_tongue  ...  pus_filled_pimples   blackheads     scurring  \
count       4920.000000  ...         4920.000000  4920.000000  4920.000000   
mean           0.021951  ...            0.021951     0.021951     0.021951   
std            0.146539  ...            0.146539     0.146539     0.146539   
min            0.000000  ...            0.000000     0.000000     0.000000   
25%            0.000000  ...            0.000000     0.000000     0.000000   
50%            0.000000  ...            0.000000     0.000000     0.000000   
75%            0.000000  ...            0.000000     0.000000     0.000000   
max            1.000000  ...            1.000000     1.000000     1.000000   

       skin_peeling  silver_like_dusting  small_dents_in_nails  \
count   4920.000000          4920.000000           4920.000000   
mean       0.023171             0.023171              0.023171   
std        0.150461             0.150461              0.150461   
min        0.000000             0.000000              0.000000   
25%        0.000000             0.000000              0.000000   
50%        0.000000             0.000000              0.000000   
75%        0.000000             0.000000              0.000000   
max        1.000000             1.000000              1.000000   

       inflammatory_nails      blister  red_sore_around_nose  \
count         4920.000000  4920.000000           4920.000000   
mean             0.023171     0.023171              0.023171   
std              0.150461     0.150461              0.150461   
min              0.000000     0.000000              0.000000   
25%              0.000000     0.000000              0.000000   
50%              0.000000     0.000000              0.000000   
75%              0.000000     0.000000              0.000000   
max              1.000000     1.000000              1.000000   

       yellow_crust_ooze  
count        4920.000000  
mean            0.023171  
std             0.150461  
min             0.000000  
25%             0.000000  
50%             0.000000  
75%             0.000000  
max             1.000000  

[8 rows x 132 columns]

In [6]:
# check for missing value
disease.isna()

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  \
0       False      False                 False                False   
1       False      False                 False                False   
2       False      False                 False                False   
3       False      False                 False                False   
4       False      False                 False                False   
...       ...        ...                   ...                  ...   
4915    False      False                 False                False   
4916    False      False                 False                False   
4917    False      False                 False                False   
4918    False      False                 False                False   
4919    False      False                 False                False   

      shivering  chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  \
0         False   False       False         False    False             False   
1         False   False       False         False    False             False   
2         False   False       False         False    False             False   
3         False   False       False         False    False             False   
4         False   False       False         False    False             False   
...         ...     ...         ...           ...      ...               ...   
4915      False   False       False         False    False             False   
4916      False   False       False         False    False             False   
4917      False   False       False         False    False             False   
4918      False   False       False         False    False             False   
4919      False   False       False         False    False             False   

      ...  blackheads  scurring  skin_peeling  silver_like_dusting  \
0     ...       False     False         False                False   
1     ...       False     False         False                False   
2     ...       False     False         False                False   
3     ...       False     False         False                False   
4     ...       False     False         False                False   
...   ...         ...       ...           ...                  ...   
4915  ...       False     False         False                False   
4916  ...       False     False         False                False   
4917  ...       False     False         False                False   
4918  ...       False     False         False                False   
4919  ...       False     False         False                False   

      small_dents_in_nails  inflammatory_nails  blister  red_sore_around_nose  \
0                    False               False    False                 False   
1                    False               False    False                 False   
2                    False               False    False                 False   
3                    False               False    False                 False   
4                    False               False    False                 False   
...                    ...                 ...      ...                   ...   
4915                 False               False    False                 False   
4916                 False               False    False                 False   
4917                 False               False    False                 False   
4918                 False               False    False                 False   
4919                 False               False    False                 False   

      yellow_crust_ooze  prognosis  
0                 False      False  
1                 False      False  
2                 False      False  
3                 False      False  
4                 False      False  
...                 ...        ...  
4915              False      False  
4916              False      False  
4917              False      False  
4918    

In [9]:
#data type
disease.dtypes

itching                  int64
skin_rash                int64
nodal_skin_eruptions     int64
continuous_sneezing      int64
shivering                int64
                         ...  
inflammatory_nails       int64
blister                  int64
red_sore_around_nose     int64
yellow_crust_ooze        int64
prognosis               object
Length: 133, dtype: object

In [ ]:
# visualize pairplot
sns.pairplot(disease)

In [10]:
# column names
disease.columns

Index(['itching', 'skin_rash', 'nodal_skin_eruptions', 'continuous_sneezing',
       'shivering', 'chills', 'joint_pain', 'stomach_pain', 'acidity',
       'ulcers_on_tongue',
       ...
       'blackheads', 'scurring', 'skin_peeling', 'silver_like_dusting',
       'small_dents_in_nails', 'inflammatory_nails', 'blister',
       'red_sore_around_nose', 'yellow_crust_ooze', 'prognosis'],
      dtype='object', length=133)

In [11]:
# define y
y=disease['prognosis']

In [12]:
# define X
x=disease[['itching', 'skin_rash', 'nodal_skin_eruptions', 'continuous_sneezing',
       'shivering', 'chills', 'joint_pain', 'stomach_pain', 'acidity',
       'ulcers_on_tongue','blackheads', 'scurring', 'skin_peeling', 'silver_like_dusting',
       'small_dents_in_nails', 'inflammatory_nails', 'blister',
       'red_sore_around_nose', 'yellow_crust_ooze']]

In [13]:
# split data
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test= train_test_split(x,y, train_size=0.7, random_state=2529)


In [14]:
# verify shape
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((3444, 19), (1476, 19), (3444,), (1476,))

In [15]:
# select model
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()

In [16]:
# train model
model.fit(x_train,y_train)

LogisticRegression()

In [17]:
# predict with model
y_pred=model.predict(x_test)

In [18]:
# model evaluation
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [19]:
# model accuracy
accuracy_score(y_test,y_pred)

0.3367208672086721

In [20]:
# model confusion matrix
print(confusion_matrix(y_test,y_pred))

[[ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0 35 ...  0  0  0]
 ...
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]]


In [21]:
# model classification report
print(classification_report(y_test,y_pred))

                                         precision    recall  f1-score   support

(vertigo) Paroymsal  Positional Vertigo       0.00      0.00      0.00        31
                                   AIDS       0.00      0.00      0.00        37
                                   Acne       1.00      1.00      1.00        35
                    Alcoholic hepatitis       0.00      0.00      0.00        40
                                Allergy       1.00      0.92      0.96        37
                              Arthritis       0.00      0.00      0.00        46
                       Bronchial Asthma       0.00      0.00      0.00        37
                   Cervical spondylosis       0.00      0.00      0.00        31
                            Chicken pox       0.76      0.97      0.85        29
                    Chronic cholestasis       0.27      0.91      0.41        32
                            Common Cold       0.92      0.92      0.92        39
                           

/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
# future prediction


In [ ]:
# define X_new
x_new = disease['itching', 'skin_rash', 'nodal_skin_eruptions', 'continuous_sneezing',
       'shivering', 'chills', 'joint_pain', 'stomach_pain', 'acidity',
       'ulcers_on_tongue','blackheads', 'scurring', 'skin_peeling', 'silver_like_dusting',
       'small_dents_in_nails', 'inflammatory_nails', 'blister',
       'red_sore_around_nose', 'yellow_crust_ooze']

In [ ]:
# predict for X_new
x_new_prd=model.predict(x_test)

array(['Chicken pox'], dtype=object)